#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CPU_COUNT="$(getconf _NPROCESSORS_ONLN 2>/dev/null || nproc 2>/dev/null || printf '4')"
if [ -z "$CPU_COUNT" ] || [ "$CPU_COUNT" -lt 1 ] 2>/dev/null; then
  CPU_COUNT=4
fi

# Cap default threads for stronger short-TC stability.
DEFAULT_THREADS="$CPU_COUNT"
if [ "$DEFAULT_THREADS" -gt 4 ]; then
  DEFAULT_THREADS=4
fi
LOW_THREADS="$DEFAULT_THREADS"
PANIC_THREADS="$(( (DEFAULT_THREADS + 1) / 2 ))"
if [ "$PANIC_THREADS" -lt 1 ]; then
  PANIC_THREADS=1
fi
CRITICAL_THREADS=1

if [ -x /usr/games/stockfish ]; then
  export STOCKFISH_THREADS="${STOCKFISH_THREADS:-$DEFAULT_THREADS}"
  export STOCKFISH_MAX_THREADS="${STOCKFISH_MAX_THREADS:-$CPU_COUNT}"
  export STOCKFISH_LOW_THREADS="${STOCKFISH_LOW_THREADS:-$LOW_THREADS}"
  export STOCKFISH_PANIC_THREADS="${STOCKFISH_PANIC_THREADS:-$PANIC_THREADS}"
  export STOCKFISH_CRITICAL_THREADS="${STOCKFISH_CRITICAL_THREADS:-$CRITICAL_THREADS}"
  export STOCKFISH_HASH_MB="${STOCKFISH_HASH_MB:-128}"
  export STOCKFISH_MOVE_OVERHEAD="${STOCKFISH_MOVE_OVERHEAD:-16}"
  export STOCKFISH_SLOW_MOVER="${STOCKFISH_SLOW_MOVER:-98}"
  export STOCKFISH_LOW_TIME_MS="${STOCKFISH_LOW_TIME_MS:-12000}"
  export STOCKFISH_LOW_TIME_OVERHEAD="${STOCKFISH_LOW_TIME_OVERHEAD:-24}"
  export STOCKFISH_LOW_TIME_SLOW="${STOCKFISH_LOW_TIME_SLOW:-78}"
  export STOCKFISH_PANIC_TIME_MS="${STOCKFISH_PANIC_TIME_MS:-1200}"
  export STOCKFISH_PANIC_OVERHEAD="${STOCKFISH_PANIC_OVERHEAD:-36}"
  export STOCKFISH_PANIC_SLOW="${STOCKFISH_PANIC_SLOW:-60}"
  export STOCKFISH_CRITICAL_TIME_MS="${STOCKFISH_CRITICAL_TIME_MS:-700}"
  export STOCKFISH_CRITICAL_OVERHEAD="${STOCKFISH_CRITICAL_OVERHEAD:-64}"
  export STOCKFISH_CRITICAL_SLOW="${STOCKFISH_CRITICAL_SLOW:-48}"
  export STOCKFISH_PROFILE_HYSTERESIS_MS="${STOCKFISH_PROFILE_HYSTERESIS_MS:-600}"
  export BOOK_DRAW_SCORE_WHITE="${BOOK_DRAW_SCORE_WHITE:-0.35}"
  export BOOK_DRAW_SCORE_BLACK="${BOOK_DRAW_SCORE_BLACK:-0.50}"
  export BOOK_PREFIX_MIN_AVG_WHITE="${BOOK_PREFIX_MIN_AVG_WHITE:-0.78}"
  export BOOK_PREFIX_MIN_AVG_BLACK="${BOOK_PREFIX_MIN_AVG_BLACK:-0.88}"
  export BOOK_POS_MIN_AVG_WHITE="${BOOK_POS_MIN_AVG_WHITE:-0.80}"
  export BOOK_POS_MIN_AVG_BLACK="${BOOK_POS_MIN_AVG_BLACK:-0.90}"
  export BOOK_PREFIX_MIN_TOTAL_WHITE="${BOOK_PREFIX_MIN_TOTAL_WHITE:-6.0}"
  export BOOK_PREFIX_MIN_TOTAL_BLACK="${BOOK_PREFIX_MIN_TOTAL_BLACK:-8.0}"
  export BOOK_POS_MIN_TOTAL_WHITE="${BOOK_POS_MIN_TOTAL_WHITE:-6.0}"
  export BOOK_POS_MIN_TOTAL_BLACK="${BOOK_POS_MIN_TOTAL_BLACK:-8.0}"
  export BOOK_PREFIX_MIN_COUNT_WHITE="${BOOK_PREFIX_MIN_COUNT_WHITE:-3}"
  export BOOK_PREFIX_MIN_COUNT_BLACK="${BOOK_PREFIX_MIN_COUNT_BLACK:-4}"
  export BOOK_POS_MIN_COUNT_WHITE="${BOOK_POS_MIN_COUNT_WHITE:-4}"
  export BOOK_POS_MIN_COUNT_BLACK="${BOOK_POS_MIN_COUNT_BLACK:-5}"
  export BOOK_PREFIX_MIN_GAP_WHITE="${BOOK_PREFIX_MIN_GAP_WHITE:-0.00}"
  export BOOK_PREFIX_MIN_GAP_BLACK="${BOOK_PREFIX_MIN_GAP_BLACK:-0.00}"
  export BOOK_POS_MIN_GAP_WHITE="${BOOK_POS_MIN_GAP_WHITE:-0.00}"
  export BOOK_POS_MIN_GAP_BLACK="${BOOK_POS_MIN_GAP_BLACK:-0.00}"
  export STOCKFISH_BIN="/usr/games/stockfish"
  exec /opt/chess-venv/bin/python3 -u "$ROOT_DIR/engine/stockfish_proxy.py"
fi

if command -v stockfish >/dev/null 2>&1; then
  export STOCKFISH_THREADS="${STOCKFISH_THREADS:-$DEFAULT_THREADS}"
  export STOCKFISH_MAX_THREADS="${STOCKFISH_MAX_THREADS:-$CPU_COUNT}"
  export STOCKFISH_LOW_THREADS="${STOCKFISH_LOW_THREADS:-$LOW_THREADS}"
  export STOCKFISH_PANIC_THREADS="${STOCKFISH_PANIC_THREADS:-$PANIC_THREADS}"
  export STOCKFISH_CRITICAL_THREADS="${STOCKFISH_CRITICAL_THREADS:-$CRITICAL_THREADS}"
  export STOCKFISH_HASH_MB="${STOCKFISH_HASH_MB:-128}"
  export STOCKFISH_MOVE_OVERHEAD="${STOCKFISH_MOVE_OVERHEAD:-16}"
  export STOCKFISH_SLOW_MOVER="${STOCKFISH_SLOW_MOVER:-98}"
  export STOCKFISH_LOW_TIME_MS="${STOCKFISH_LOW_TIME_MS:-12000}"
  export STOCKFISH_LOW_TIME_OVERHEAD="${STOCKFISH_LOW_TIME_OVERHEAD:-24}"
  export STOCKFISH_LOW_TIME_SLOW="${STOCKFISH_LOW_TIME_SLOW:-78}"
  export STOCKFISH_PANIC_TIME_MS="${STOCKFISH_PANIC_TIME_MS:-1200}"
  export STOCKFISH_PANIC_OVERHEAD="${STOCKFISH_PANIC_OVERHEAD:-36}"
  export STOCKFISH_PANIC_SLOW="${STOCKFISH_PANIC_SLOW:-60}"
  export STOCKFISH_CRITICAL_TIME_MS="${STOCKFISH_CRITICAL_TIME_MS:-700}"
  export STOCKFISH_CRITICAL_OVERHEAD="${STOCKFISH_CRITICAL_OVERHEAD:-64}"
  export STOCKFISH_CRITICAL_SLOW="${STOCKFISH_CRITICAL_SLOW:-48}"
  export STOCKFISH_PROFILE_HYSTERESIS_MS="${STOCKFISH_PROFILE_HYSTERESIS_MS:-600}"
  export BOOK_DRAW_SCORE_WHITE="${BOOK_DRAW_SCORE_WHITE:-0.35}"
  export BOOK_DRAW_SCORE_BLACK="${BOOK_DRAW_SCORE_BLACK:-0.50}"
  export BOOK_PREFIX_MIN_AVG_WHITE="${BOOK_PREFIX_MIN_AVG_WHITE:-0.78}"
  export BOOK_PREFIX_MIN_AVG_BLACK="${BOOK_PREFIX_MIN_AVG_BLACK:-0.88}"
  export BOOK_POS_MIN_AVG_WHITE="${BOOK_POS_MIN_AVG_WHITE:-0.80}"
  export BOOK_POS_MIN_AVG_BLACK="${BOOK_POS_MIN_AVG_BLACK:-0.90}"
  export BOOK_PREFIX_MIN_TOTAL_WHITE="${BOOK_PREFIX_MIN_TOTAL_WHITE:-6.0}"
  export BOOK_PREFIX_MIN_TOTAL_BLACK="${BOOK_PREFIX_MIN_TOTAL_BLACK:-8.0}"
  export BOOK_POS_MIN_TOTAL_WHITE="${BOOK_POS_MIN_TOTAL_WHITE:-6.0}"
  export BOOK_POS_MIN_TOTAL_BLACK="${BOOK_POS_MIN_TOTAL_BLACK:-8.0}"
  export BOOK_PREFIX_MIN_COUNT_WHITE="${BOOK_PREFIX_MIN_COUNT_WHITE:-3}"
  export BOOK_PREFIX_MIN_COUNT_BLACK="${BOOK_PREFIX_MIN_COUNT_BLACK:-4}"
  export BOOK_POS_MIN_COUNT_WHITE="${BOOK_POS_MIN_COUNT_WHITE:-4}"
  export BOOK_POS_MIN_COUNT_BLACK="${BOOK_POS_MIN_COUNT_BLACK:-5}"
  export BOOK_PREFIX_MIN_GAP_WHITE="${BOOK_PREFIX_MIN_GAP_WHITE:-0.00}"
  export BOOK_PREFIX_MIN_GAP_BLACK="${BOOK_PREFIX_MIN_GAP_BLACK:-0.00}"
  export BOOK_POS_MIN_GAP_WHITE="${BOOK_POS_MIN_GAP_WHITE:-0.00}"
  export BOOK_POS_MIN_GAP_BLACK="${BOOK_POS_MIN_GAP_BLACK:-0.00}"
  export STOCKFISH_BIN="stockfish"
  exec /opt/chess-venv/bin/python3 -u "$ROOT_DIR/engine/stockfish_proxy.py"
fi

exec /opt/chess-venv/bin/python3 -u "$ROOT_DIR/engine/fallback_engine.py"
