#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CPU_COUNT="$(getconf _NPROCESSORS_ONLN 2>/dev/null || nproc 2>/dev/null || printf '4')"
if [ -z "$CPU_COUNT" ] || [ "$CPU_COUNT" -lt 1 ] 2>/dev/null; then
  CPU_COUNT=4
fi

# Cap default threads for stronger short-TC stability.
DEFAULT_THREADS="$CPU_COUNT"
if [ "$DEFAULT_THREADS" -gt 4 ]; then
  DEFAULT_THREADS=4
fi

if [ -x /usr/games/stockfish ]; then
  export STOCKFISH_THREADS="${STOCKFISH_THREADS:-$DEFAULT_THREADS}"
  export STOCKFISH_MAX_THREADS="${STOCKFISH_MAX_THREADS:-$CPU_COUNT}"
  export STOCKFISH_HASH_MB="${STOCKFISH_HASH_MB:-256}"
  export STOCKFISH_MOVE_OVERHEAD="${STOCKFISH_MOVE_OVERHEAD:-20}"
  export STOCKFISH_SLOW_MOVER="${STOCKFISH_SLOW_MOVER:-90}"
  export STOCKFISH_LOW_TIME_MS="${STOCKFISH_LOW_TIME_MS:-12000}"
  export STOCKFISH_LOW_TIME_OVERHEAD="${STOCKFISH_LOW_TIME_OVERHEAD:-28}"
  export STOCKFISH_LOW_TIME_SLOW="${STOCKFISH_LOW_TIME_SLOW:-70}"
  export STOCKFISH_PANIC_TIME_MS="${STOCKFISH_PANIC_TIME_MS:-1200}"
  export STOCKFISH_PANIC_OVERHEAD="${STOCKFISH_PANIC_OVERHEAD:-40}"
  export STOCKFISH_PANIC_SLOW="${STOCKFISH_PANIC_SLOW:-55}"
  export STOCKFISH_CRITICAL_TIME_MS="${STOCKFISH_CRITICAL_TIME_MS:-700}"
  export STOCKFISH_CRITICAL_OVERHEAD="${STOCKFISH_CRITICAL_OVERHEAD:-70}"
  export STOCKFISH_CRITICAL_SLOW="${STOCKFISH_CRITICAL_SLOW:-45}"
  export STOCKFISH_PROFILE_HYSTERESIS_MS="${STOCKFISH_PROFILE_HYSTERESIS_MS:-600}"
  export STOCKFISH_BIN="/usr/games/stockfish"
  exec /opt/chess-venv/bin/python3 -u "$ROOT_DIR/engine/stockfish_proxy.py"
fi

if command -v stockfish >/dev/null 2>&1; then
  export STOCKFISH_THREADS="${STOCKFISH_THREADS:-$DEFAULT_THREADS}"
  export STOCKFISH_MAX_THREADS="${STOCKFISH_MAX_THREADS:-$CPU_COUNT}"
  export STOCKFISH_HASH_MB="${STOCKFISH_HASH_MB:-256}"
  export STOCKFISH_MOVE_OVERHEAD="${STOCKFISH_MOVE_OVERHEAD:-20}"
  export STOCKFISH_SLOW_MOVER="${STOCKFISH_SLOW_MOVER:-90}"
  export STOCKFISH_LOW_TIME_MS="${STOCKFISH_LOW_TIME_MS:-12000}"
  export STOCKFISH_LOW_TIME_OVERHEAD="${STOCKFISH_LOW_TIME_OVERHEAD:-28}"
  export STOCKFISH_LOW_TIME_SLOW="${STOCKFISH_LOW_TIME_SLOW:-70}"
  export STOCKFISH_PANIC_TIME_MS="${STOCKFISH_PANIC_TIME_MS:-1200}"
  export STOCKFISH_PANIC_OVERHEAD="${STOCKFISH_PANIC_OVERHEAD:-40}"
  export STOCKFISH_PANIC_SLOW="${STOCKFISH_PANIC_SLOW:-55}"
  export STOCKFISH_CRITICAL_TIME_MS="${STOCKFISH_CRITICAL_TIME_MS:-700}"
  export STOCKFISH_CRITICAL_OVERHEAD="${STOCKFISH_CRITICAL_OVERHEAD:-70}"
  export STOCKFISH_CRITICAL_SLOW="${STOCKFISH_CRITICAL_SLOW:-45}"
  export STOCKFISH_PROFILE_HYSTERESIS_MS="${STOCKFISH_PROFILE_HYSTERESIS_MS:-600}"
  export STOCKFISH_BIN="stockfish"
  exec /opt/chess-venv/bin/python3 -u "$ROOT_DIR/engine/stockfish_proxy.py"
fi

exec /opt/chess-venv/bin/python3 -u "$ROOT_DIR/engine/fallback_engine.py"
